// AUTO-GENERATED by scripts/generate-guided-tour.js — DO NOT EDIT BY HAND.
// Regenerated on every prebuild (after sync-files.js + generate-research-files.js).
// Source: scripts/tour-chapters.json (sidecar).
// Validation: every entry references a file in /public/files/ or /public/images/.
//
// To add a new tour chapter:
//   1. Drop the artifact in /download/
//   2. Run `bun run sync-files` (or rely on prebuild)
//   3. Add an entry to scripts/tour-chapters.json with {chapter, narrative, why, order}
//   4. Re-run `bun run prebuild` — this file regenerates.

import type { TourStop } from './subpage-data'

export const GUIDED_TOUR_GENERATED: TourStop[] = [
  {
    fileName: "architecture_diagram.png",
    chapter: "Chapter 1 — The Vision",
    narrative: "Before writing a single line of recovery code, we draw the system. This diagram shows the three-tier defense: Prevention (pre-flight checks), Detection (real-time monitoring), Recovery (auto-clean + checkpoint restore).",
    why: "Architecture-first design forces you to name every failure path before you encounter it. Recovery code written without a diagram is just fire-fighting with extra steps.",
  },
  {
    fileName: "impeccable-error-handler/README.md",
    chapter: "Chapter 2 — The Design",
    narrative: "The README documents the three-tier system in plain prose. It is the contract between the code and the operator. Every behavior the system promises lives here first.",
    why: "A README is a stress test for clarity. If you cannot explain the system in three paragraphs, you have not designed it — you have only coded it.",
  },
  {
    fileName: "impeccable-error-handler/deploy.sh",
    chapter: "Chapter 3 — The Implementation",
    narrative: "The main deployment script: pre-flight checks, session checkpointing, and failover logic. Every line is a defense against a specific failure mode observed in production.",
    why: "Shell scripts are honest — they cannot hide complexity behind abstractions. Reading deploy.sh end-to-end is the fastest way to understand what the system actually does.",
  },
  {
    fileName: "impeccable-error-handler/git-recovery.sh",
    chapter: "Chapter 4 — The Recovery",
    narrative: "When git state corrupts (rebase locks, merge conflicts, index corruption), this script restores from checkpoint. It is the system's immune response — automatic, fast, and predictable.",
    why: "Recovery code is more important than happy-path code. Users forgive a system that fails gracefully; they abandon one that fails and stays failed.",
  },
  {
    fileName: "Impeccable_Error_Fix_Handler_Audit.pdf",
    chapter: "Chapter 5 — The Audit",
    narrative: "Five animal-metaphor perspectives (Owl, Eagle, Beaver, Dolphin, Elephant) examine the system for hidden factors. Each finds what the others miss.",
    why: "Single-perspective audits are blind to their own assumptions. Multi-perspective audits surface contradictions that point to the deepest truths about a system.",
  },
  {
    fileName: "generate_audit.py",
    chapter: "Chapter 6 — The Audit Generator",
    narrative: "The Python script that generates the audit PDF using ReportLab. Reading it reveals how the audit's structure itself encodes the analytical framework — every flowable is a perspective.",
    why: "The generator is documentation that runs itself. When the audit changes, the script makes the change visible — unlike a static PDF, it shows its own construction.",
  },
  {
    fileName: "Portfolio_Website_Recreation_SOP_final.pdf",
    chapter: "Chapter 7 — The Full Story",
    narrative: "The 33-page Standard Operating Procedure: 3 design approaches, confidence scoring, decision trees, YC-partner and staff-engineer reviews. This is the canonical document for recreating the entire portfolio.",
    why: "A SOP is the highest leverage artifact a developer can produce. It converts tacit knowledge into reproducible process — the difference between a project and a practice.",
  },
  {
    fileName: "cover_portfolio_sop.html",
    chapter: "Chapter 8 — The Cover",
    narrative: "The HTML cover for the SOP. Inline-viewable in any browser, no PDF reader required. A small kindness for mobile readers who hate downloading PDFs.",
    why: "Format choice is accessibility. The same content in HTML, PDF, and PNG reaches three audiences: the impatient, the archivist, and the visual learner.",
  },
  {
    fileName: "generate_portfolio_sop.py",
    chapter: "Chapter 9 — The SOP Generator",
    narrative: "The script that generates the SOP PDF. Custom ReportLab styles, flowables, and table builders. Reading it teaches you how to programmatically produce a 33-page document with consistent typography.",
    why: "Programmatic document generation is a superpower. Every resume, every report, every proposal can be regenerated from data — never out of date, never inconsistent.",
  },
  {
    fileName: "gen_architecture.py",
    chapter: "Chapter 10 — The Architecture Generator",
    narrative: "Generates the architecture diagram (Chapter 1) programmatically. The diagram is not a static artifact — it is code, versionable and reproducible.",
    why: "Diagrams as code is the only sustainable architecture documentation practice. Whiteboard photos rot, Visio files rot, but Python that draws the same picture every commit does not.",
  },
  {
    fileName: "generate_decision_tree.py",
    chapter: "Chapter 11 — The Decision Tree Generator",
    narrative: "Generates the decision tree that helps choose between proxy architectures and design approaches. Encodes the same trade-offs the SOP discusses — but as a visual query.",
    why: "A decision tree is a conversation with your future self. When you forget why you chose X over Y, the tree reminds you — and shows what would have to change to flip the decision.",
  },
  {
    fileName: "decision_tree.png",
    chapter: "Chapter 12 — The Decision Tree",
    narrative: "The rendered decision tree. Start at the root, follow your constraints, arrive at a recommended architecture. Three branches: portfolio, microservices, enterprise.",
    why: "Visual decisions are auditable decisions. Stakeholders can point to a node and say \"this is wrong\" — a conversation that is impossible with prose rationales.",
  },
  {
    fileName: "design_approaches.png",
    chapter: "Chapter 13 — Three Design Approaches",
    narrative: "Brutalist Industrial, Organic Minimalism, Cyberpunk Dashboard. Same content, three wildly different presentations. The point: design is not about what to say, but how to say it.",
    why: "Generating the same artifact in three styles is the cheapest way to surface your actual design preferences. The approach you reject tells you more than the one you choose.",
  },
  {
    fileName: "error-handler-tab.png",
    chapter: "Chapter 14 — The Error Handler UI",
    narrative: "The pre-flight deployment checker and error handler interface. Visible resilience — users see the checks running, not just their outcome.",
    why: "Visible resilience builds trust. Hidden resilience builds suspicion. Users who never see the system work assume it does not work — even when it does.",
  },
  {
    fileName: "perspectives-tab.png",
    chapter: "Chapter 15 — The Five Perspectives",
    narrative: "The five animal-metaphor perspectives rendered as a single comparison view. Owl, Eagle, Beaver, Dolphin, Elephant — each lens adds a dimension the others cannot see.",
    why: "A 2D table of 5 perspectives surfaces contradictions that bullet lists hide. The contradictions are where the deepest insights live.",
  },
  {
    fileName: "proxy-topics-page.png",
    chapter: "Chapter 16 — The Proxy Discussion",
    narrative: "The proxy types comparison and discussion page. Six proxies, fit-scored against the portfolio use case. Reverse (90%) and Resilience (85%) win; Service Mesh (15%) and Transparent (10%) lose.",
    why: "A fit-scored comparison converts \"it depends\" into \"it depends on X, Y, Z — and here are the values\". The next person does not have to re-derive your reasoning.",
  },
  {
    fileName: "Portfolio_Website_Recreation_SOP.pdf",
    chapter: "Chapter 17 — The Earlier Draft",
    narrative: "The earlier draft of the SOP, kept for version comparison. Comparing draft and final reveals which decisions hardened and which stayed soft.",
    why: "Keeping drafts is keeping your own decision history. The delta between draft and final is the most honest record of what you learned during the project.",
  },
  {
    fileName: "cover_portfolio_sop.pdf",
    chapter: "Chapter 18 — The Cover PDF",
    narrative: "The standalone cover page as PDF. Useful for embedding in other documents, slide decks, or printing as a title page for a physical binder.",
    why: "Artifacts should be composable. A cover that works as HTML, PDF, and print reaches three audiences with zero extra work — the holy grail of format polyglotism.",
  },
  {
    fileName: "README.md",
    chapter: "Chapter 19 — Project Readme",
    narrative: "The project README. Live links to both deployments, tech stack, project structure, interactive demos, design philosophy, and case studies. The front door for any new visitor.",
    why: "A README is the only document every visitor will read. Optimize it for the visitor who spends 30 seconds and decides whether to stay — then add depth for the one who stays 30 minutes.",
  },
]

// Stats for build log visibility
export const GUIDED_TOUR_STATS = {
  total: 19,
  missingFiles: 0,
  orphanedFiles: 19,
  generatedAt: 1783143651428,
}
