// AUTO-GENERATED by scripts/generate-research-files.js — DO NOT EDIT BY HAND.
// Regenerated on every prebuild (sync-files.js runs first, then this script).
// Source: /public/files/* and /public/images/* (filtered).
// Descriptions: scripts/file-descriptions.json (sidecar).
//
// To add a new artifact:
//   1. Drop the file in /download/
//   2. Run `bun run sync-files` (or rely on prebuild)
//   3. Add a description entry to scripts/file-descriptions.json
//   4. Re-run `bun run prebuild` — this file regenerates.

import { assetPath } from './utils'
import type { ProjectFile } from './subpage-data'

export const RESEARCH_FILES_GENERATED: ProjectFile[] = [
  {
    name: "architecture_diagram.png",
    type: "image",
    size: 270760,
    path: assetPath("/images/architecture_diagram.png"),
    description: "System architecture diagram showing the three-tier error defense system",
  },
  {
    name: "decision_tree.png",
    type: "image",
    size: 169654,
    path: assetPath("/images/decision_tree.png"),
    description: "Decision tree for choosing the right proxy architecture and design approach",
  },
  {
    name: "design_approaches.png",
    type: "image",
    size: 178395,
    path: assetPath("/images/design_approaches.png"),
    description: "Three wildly different design approaches: Brutalist Industrial, Organic Minimalism, Cyberpunk Dashboard",
  },
  {
    name: "error-handler-tab.png",
    type: "image",
    size: 84897,
    path: assetPath("/images/error-handler-tab.png"),
    description: "Pre-flight deployment checker and error handler interface design",
  },
  {
    name: "perspectives-tab.png",
    type: "image",
    size: 63867,
    path: assetPath("/images/perspectives-tab.png"),
    description: "Five animal-metaphor perspectives on error handling and resilience",
  },
  {
    name: "proxy-topics-page.png",
    type: "image",
    size: 81708,
    path: assetPath("/images/proxy-topics-page.png"),
    description: "Proxy types comparison and discussion page visualization",
  },
  {
    name: "cover_portfolio_sop.pdf",
    type: "pdf",
    size: 59959,
    path: assetPath("/files/cover_portfolio_sop.pdf"),
    description: "Standalone cover page for the Portfolio Website Recreation SOP document",
  },
  {
    name: "Impeccable_Error_Fix_Handler_Audit.pdf",
    type: "pdf",
    size: 84542,
    path: assetPath("/files/Impeccable_Error_Fix_Handler_Audit.pdf"),
    description: "Comprehensive audit report with 5 animal-metaphor perspectives (Owl, Eagle, Beaver, Dolphin, Elephant)",
  },
  {
    name: "Portfolio_Website_Recreation_SOP_final.pdf",
    type: "pdf",
    size: 764512,
    path: assetPath("/files/Portfolio_Website_Recreation_SOP_final.pdf"),
    description: "33-page SOP for recreating the portfolio with 3 design approaches, confidence scoring, decision trees, YC/staff-engineer reviews",
  },
  {
    name: "Portfolio_Website_Recreation_SOP.pdf",
    type: "pdf",
    size: 705303,
    path: assetPath("/files/Portfolio_Website_Recreation_SOP.pdf"),
    description: "Earlier draft of the SOP — included for version comparison and historical reference",
  },
  {
    name: "gen_architecture.py",
    type: "script",
    size: 19127,
    path: assetPath("/files/gen_architecture.py"),
    description: "Python script generating the system architecture diagram visualization",
  },
  {
    name: "generate_audit.py",
    type: "script",
    size: 51310,
    path: assetPath("/files/generate_audit.py"),
    description: "Python script generating the Error Fix Handler Audit PDF with cascade palette",
  },
  {
    name: "generate_decision_tree.py",
    type: "script",
    size: 11539,
    path: assetPath("/files/generate_decision_tree.py"),
    description: "Python script generating the decision tree visualization for proxy and design approach selection",
  },
  {
    name: "generate_portfolio_sop.py",
    type: "script",
    size: 89832,
    path: assetPath("/files/generate_portfolio_sop.py"),
    description: "Python script generating the SOP PDF with custom ReportLab styles, flowables, and table builders",
  },
  {
    name: "impeccable-error-handler/deploy.sh",
    type: "shell",
    size: 17570,
    path: assetPath("/files/impeccable-error-handler/deploy.sh"),
    description: "Main deployment script with pre-flight checks, session checkpointing, and failover logic",
  },
  {
    name: "impeccable-error-handler/git-recovery.sh",
    type: "shell",
    size: 4746,
    path: assetPath("/files/impeccable-error-handler/git-recovery.sh"),
    description: "Git state recovery script for handling rebase locks, merge conflicts, and index corruption",
  },
  {
    name: "cover_portfolio_sop.html",
    type: "document",
    size: 5394,
    path: assetPath("/files/cover_portfolio_sop.html"),
    description: "HTML version of the SOP cover page — viewable inline in the browser",
  },
  {
    name: "impeccable-error-handler/README.md",
    type: "document",
    size: 2747,
    path: assetPath("/files/impeccable-error-handler/README.md"),
    description: "Documentation for the three-tier error defense system: Prevention, Detection, Recovery",
  },
  {
    name: "README.md",
    type: "document",
    size: 34,
    path: assetPath("/files/README.md"),
    description: "Project README — live deployment links, tech stack, project structure, design philosophy",
  },
]

// Stats for build log visibility
export const RESEARCH_FILES_STATS = {
  total: 19,
  byType: {
  "image": 6,
  "pdf": 4,
  "script": 4,
  "shell": 2,
  "document": 3
},
  generatedAt: 1783143651350,
}
